Output res/out/midimon.gif

Set FontSize 18
Set FontFamily "JetBrains Mono"
Set Width 1000
Set Height 1000

Type "aud midimon --script=./lua/examples/midimon"
Sleep 500ms
Enter
Sleep 250ms

Type "?"
Sleep 4s
Type "q"

Type "a"
Sleep 4s
Type "q"

Type "d"
Sleep 4s
Type "q"

Type "l"
Sleep 250ms
Type "j"
Sleep 250ms
Enter
Sleep 250ms
Type "s"
Sleep 5s
Type "q"

Sleep 250ms
Type "h"
Sleep 250ms
Enter
Sleep 5s

Type "q"
